### ISSUE TITLE
Base64 encoding not always determined

### ISSUE THREAD

**Issue by ghost** [k4m4/dcipher-cli#2]
`cGFzc3dvcmQy` (base64 for `password2`) string returns `✖ Hash type not supported`
The problem probably lies in [this regex](https://github.com/kevva/base64-regex/blob/0f0065cb1a1c75dc13c603c424f19103a2294782/index.js#L5)

**Comment by thanasisk** [comment]
since when base64 is a one-way hash algorithm?

**Comment by k4m4** [comment]
Hi there @alexmozzhakov. As you already mentioned, it seems that this is a problem with the [base64-regex](https://github.com/kevva/base64-regex) repo by [kevva](https://github.com/kevva). I'll make a PR with a fix on the repo asap, in the hopes of a quick reply (& merge). Thanks for bringing this up!

**Comment by alexmozzhakov** [comment]
@k4m4 actually, seems like an open issue https://github.com/kevva/base64-regex/issues/4

**Comment by Satyamboss1** [comment]
Is it possible
